name: MagicSpells
main: com.nisovin.magicspells.MagicSpells
version: $version
authors: [nisovin, TheComputerGeek2, Chronoken]
softdepend: [GriefPrevention,Vault,ProtocolLib,WorldGuard,Residence,PowerNBT,LibsDisguises,NoCheatPlus,PlaceholderAPI]
api-version: "1.13"